spring.application.name=demo
//Nergisten al?nan veri taban? bilgileri buraya girilecek
spring.datasource.url=jdbc:postgresql://localhost:5432/dijital_icerik_db
spring.datasource.username=postgres
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
