DROP TABLE IF EXISTS user_contents;
DROP TABLE IF EXISTS subscriptions;
DROP TABLE IF EXISTS contents;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    full_name VARCHAR(255),
    role VARCHAR(50) NOT NULL
);

CREATE TABLE contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    thumbnail_url VARCHAR(500) NOT NULL,
    duration_minutes INT NOT NULL,
    premium BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_name VARCHAR(120) NOT NULL,
    price DOUBLE PRECISION NOT NULL,
    currency VARCHAR(10) NOT NULL,
    billing_cycle VARCHAR(30) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    user_id BIGINT NOT NULL,
    CONSTRAINT fk_subscription_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE user_contents (
    user_id BIGINT NOT NULL,
    content_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, content_id),
    CONSTRAINT fk_user_contents_user
        FOREIGN KEY (user_id) REFERENCES users(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_contents_content
        FOREIGN KEY (content_id) REFERENCES contents(id)
        ON DELETE CASCADE
);
